set -s escape-time 0

set-option -g allow-passthrough on
set-option -g set-titles on
set -ga terminal-features "*:hyperlinks"
set -a terminal-features 'xterm-256color:RGB'
set -sa terminal-features ',xterm-ghostty:RGB'
set -g focus-events on

unbind C-b
set -g prefix C-]
bind C-] send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Mouse
set -g mouse on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-resurrect settings
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# tmux-continuum settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set-option -g renumber-windows on

# Source local overrides if present
if-shell "[ -f ~/.tmux_local.conf ]" "source-file ~/.tmux_local.conf"

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
